"""Electrical power + wire activity simulation for the virtual logic PC.

This module now runs a strongly analog-oriented machine model:
- power rails and wires are voltages with RC settling,
- clock is generated by an RC + Schmitt-like oscillator,
- RAM cells are stored as analog node voltages with leakage,
- digital subsystems read/write through thresholding.
"""

from __future__ import annotations

from dataclasses import dataclass
import math

from simulation.full_spice_mna import SpiceMNA
from simulation.logic_cpu import SimpleLogicCPU


@dataclass
class PowerSpec:
    voltage_v: float = 5.0
    required_voltage_v: float = 4.8
    available_current_a: float = 1.2
    required_current_a: float = 0.8


class ElectricalSystem:
    """Keeps power, current and signal timing state with analog dynamics."""

    WIRE_KEYS = (
        "power_bus",
        "clock_line",
        "control_line",
        "alu_bus",
        "memory_bus",
        "video_line",
        "ram_line",
        "hdd_line",
        "ram_screen_line",
    )

    def __init__(self, cpu: SimpleLogicCPU) -> None:
        self.cpu = cpu
        self.power = PowerSpec()
        self.power_switch_on = False
        self.uptime_sec = 0.0
        self.booted = False

        # RC analog wires (V). UI still consumes boolean activity from thresholding.
        self.wire_voltage: dict[str, float] = {k: 0.0 for k in self.WIRE_KEYS}
        self.wire_states: dict[str, bool] = {k: False for k in self.WIRE_KEYS}
        self.line_tau_sec = 0.010
        self.logic_high_threshold_v = 2.5
        self.use_mna_wire_solver = True

        # RC clock oscillator (single-node Schmitt approximation).
        self.clock_cap_v = 0.0
        self.clock_level = 0
        self.clock_hz_estimate = 0.0
        self._clock_charge = True
        self._clock_last_edge_time = 0.0
        self._clock_rc_tau_sec = 0.12
        self._clock_high_trip_v = 3.2
        self._clock_low_trip_v = 1.8

        # Analog RAM (256 bytes x 8 bitcells as voltages).
        self.ram_size = 256
        self.ram_bits: list[list[float]] = [[0.0] * 8 for _ in range(self.ram_size)]
        self.ram_leak_tau_sec = 45.0
        self.hdd_sector_size = 16
        self.hdd_sector_count = 32
        self.hdd: dict[int, bytes] = {
            i: bytes(self.hdd_sector_size) for i in range(self.hdd_sector_count)
        }

        self.last_ram_addr = 0
        self.last_ram_value = 0
        self.last_hdd_sector = 0
        self.ram_reads = 0
        self.ram_writes = 0
        self.hdd_writes = 0
        self._last_synced_cycle = -1

        # Full MNA wire solver used by GUI-facing lines.
        self._wire_mna = self._build_wire_mna()
        self._wire_node_map = {
            "power_bus": "w_power_bus",
            "clock_line": "w_clock_line",
            "control_line": "w_control_line",
            "alu_bus": "w_alu_bus",
            "memory_bus": "w_memory_bus",
            "video_line": "w_video_line",
            "ram_line": "w_ram_line",
            "hdd_line": "w_hdd_line",
            "ram_screen_line": "w_ram_screen_line",
        }
        self._wire_src_map = {
            "power_bus": "D_power_bus",
            "clock_line": "D_clock_line",
            "control_line": "D_control_line",
            "alu_bus": "D_alu_bus",
            "memory_bus": "D_memory_bus",
            "video_line": "D_video_line",
            "ram_line": "D_ram_line",
            "hdd_line": "D_hdd_line",
            "ram_screen_line": "D_ram_screen_line",
        }
        self._wire_guess: dict[str, float] = {}

    @property
    def enough_voltage(self) -> bool:
        return self.power.voltage_v >= self.power.required_voltage_v

    @property
    def enough_current(self) -> bool:
        return self.power.available_current_a >= self.power.required_current_a

    @property
    def powered(self) -> bool:
        return self.power_switch_on and self.enough_voltage

    @property
    def boot_ready(self) -> bool:
        return self.powered and self.enough_current

    @property
    def power_message(self) -> str:
        if not self.power_switch_on:
            return "Power switch is OFF"
        if not self.enough_voltage:
            return "Voltage is too low to start"
        if not self.enough_current:
            return "Current is too low to boot CPU"
        return "System online"

    def set_available_current(self, value: float) -> None:
        self.power.available_current_a = max(0.0, float(value))

    def toggle_power(self) -> None:
        self.power_switch_on = not self.power_switch_on
        if not self.power_switch_on:
            self._hard_reset()

    def _hard_reset(self) -> None:
        self.booted = False
        self.uptime_sec = 0.0
        self.clock_cap_v = 0.0
        self.clock_level = 0
        self.clock_hz_estimate = 0.0
        self._clock_charge = True
        self._clock_last_edge_time = 0.0

        # RAM is volatile; HDD remains persistent across power cycles.
        self.ram_bits = [[0.0] * 8 for _ in range(self.ram_size)]
        self.last_ram_addr = 0
        self.last_ram_value = 0
        self._last_synced_cycle = -1

        for wire in self.WIRE_KEYS:
            self.wire_voltage[wire] = 0.0
            self.wire_states[wire] = False
            self._wire_guess[self._wire_node_map[wire]] = 0.0
            self._wire_mna.set_voltage_source(self._wire_src_map[wire], 0.0)

        self.cpu.reset()

    def _build_wire_mna(self) -> SpiceMNA:
        mna = SpiceMNA()
        mna.add_voltage_source("VDD", "vdd", "0", self.power.voltage_v)
        for key in self.WIRE_KEYS:
            src = f"src_{key}"
            mid = f"m_{key}"
            out = f"w_{key}"
            drv = f"D_{key}"
            mna.add_voltage_source(drv, src, "0", 0.0)

            # Non-inverting CMOS buffer as two cascaded inverters.
            mna.add_mosfet(d=mid, g=src, s="0", b="0", mtype="n", beta=2e-4, vth=0.7, lamb=0.02)
            mna.add_mosfet(d=mid, g=src, s="vdd", b="vdd", mtype="p", beta=1.2e-4, vth=-0.7, lamb=0.02)
            mna.add_mosfet(d=out, g=mid, s="0", b="0", mtype="n", beta=2e-4, vth=0.7, lamb=0.02)
            mna.add_mosfet(d=out, g=mid, s="vdd", b="vdd", mtype="p", beta=1.2e-4, vth=-0.7, lamb=0.02)

            # RC line loading for smooth analog behavior.
            mna.add_resistor(out, "0", 1e9)
            mna.add_capacitor(out, "0", 2e-11)

        return mna

    @staticmethod
    def _rc_step(v_now: float, v_target: float, dt_sec: float, tau_sec: float) -> float:
        if tau_sec <= 0.0:
            return v_target
        alpha = 1.0 - math.exp(-dt_sec / tau_sec)
        return v_now + (v_target - v_now) * alpha

    def _set_wire_drive(self, key: str, high: bool, dt_sec: float) -> None:
        target = self.power.voltage_v if high and self.powered else 0.0
        self.wire_voltage[key] = self._rc_step(
            self.wire_voltage[key],
            target,
            dt_sec,
            self.line_tau_sec,
        )

    def _refresh_wire_thresholds(self) -> None:
        for key in self.WIRE_KEYS:
            self.wire_states[key] = self.wire_voltage[key] >= self.logic_high_threshold_v

    def _update_analog_clock(self, dt_sec: float) -> bool:
        """Update RC oscillator; return True on rising edge."""
        target = self.power.voltage_v if self._clock_charge else 0.0
        self.clock_cap_v = self._rc_step(
            self.clock_cap_v,
            target,
            dt_sec,
            self._clock_rc_tau_sec,
        )

        rising = False
        if self.clock_level == 0 and self.clock_cap_v >= self._clock_high_trip_v:
            self.clock_level = 1
            self._clock_charge = False
            rising = True
        elif self.clock_level == 1 and self.clock_cap_v <= self._clock_low_trip_v:
            self.clock_level = 0
            self._clock_charge = True

        if rising:
            if self._clock_last_edge_time > 0.0:
                period = max(1e-6, self.uptime_sec - self._clock_last_edge_time)
                self.clock_hz_estimate = 1.0 / period
            self._clock_last_edge_time = self.uptime_sec

        return rising

    def _ram_bit_from_voltage(self, v: float) -> int:
        return 1 if v >= self.logic_high_threshold_v else 0

    def _read_ram_byte(self, addr: int) -> int:
        bits = self.ram_bits[addr & 0xFF]
        value = 0
        for i in range(8):
            value |= self._ram_bit_from_voltage(bits[i]) << i
        return value & 0xFF

    def _write_ram_byte(self, addr: int, value: int) -> None:
        row = self.ram_bits[addr & 0xFF]
        for i in range(8):
            bit = (value >> i) & 1
            row[i] = self.power.voltage_v if bit else 0.0

    def _ram_leak(self, dt_sec: float) -> None:
        if self.ram_leak_tau_sec <= 0.0:
            return
        keep = math.exp(-dt_sec / self.ram_leak_tau_sec)
        for row in self.ram_bits:
            for i, v in enumerate(row):
                row[i] = max(0.0, v * keep)

    def update(self, dt_sec: float) -> None:
        if not self.powered:
            self._hard_reset()
            return

        self.uptime_sec += dt_sec
        self._ram_leak(dt_sec)

        if not self.boot_ready:
            self.booted = False
            drives = {key: (key == "power_bus") for key in self.WIRE_KEYS}
            self._update_wire_mna(drives, dt_sec)
            return

        self.booted = True

        # Analog clock node and CPU sampling on rising edge.
        rising = self._update_analog_clock(dt_sec)
        if rising:
            self.cpu.tick_rising_edge()

        # Desired digital activity from CPU state (drives analog wires).
        drives = {
            "power_bus": True,
            "clock_line": bool(self.clock_level),
            "control_line": self.cpu.phase in {"FETCH", "DECODE"},
            "alu_bus": self.cpu.phase == "EXECUTE",
            "memory_bus": self.cpu.phase in {"FETCH", "WRITEBACK"},
            "video_line": True,
            "ram_line": False,
            "hdd_line": False,
            "ram_screen_line": True,
        }

        self._tick_memory_devices(drives)

        self._update_wire_mna(drives, dt_sec)

    def _update_wire_mna(self, drives: dict[str, bool], dt_sec: float) -> None:
        if not self.use_mna_wire_solver:
            for key, high in drives.items():
                self._set_wire_drive(key, high, dt_sec)
            self._refresh_wire_thresholds()
            return

        self._wire_mna.set_voltage_source("VDD", self.power.voltage_v if self.powered else 0.0)
        for key, high in drives.items():
            self._wire_mna.set_voltage_source(
                self._wire_src_map[key],
                self.power.voltage_v if (high and self.powered) else 0.0,
            )

        # One transient step per simulation tick; voltages are read by GUI directly.
        result = self._wire_mna.solve_transient(
            tstop_sec=max(dt_sec, 1e-5),
            dt_sec=max(dt_sec, 1e-5),
            initial_guess=self._wire_guess,
        )[-1]
        if result.converged:
            self._wire_guess = dict(result.voltages)

        for key, node in self._wire_node_map.items():
            v = result.voltages.get(node, self.wire_voltage[key]) if result.converged else self.wire_voltage[key]
            self.wire_voltage[key] = v
            self.wire_states[key] = v >= self.logic_high_threshold_v

    def _tick_memory_devices(self, drives: dict[str, bool]) -> None:
        """Drive RAM/HDD activity from CPU phase for visualization and diagnostics."""
        addr = self.cpu.pc.value & 0xFF

        if self.cpu.phase in {"FETCH", "DECODE"}:
            value = self._read_ram_byte(addr)
            self.last_ram_addr = addr
            self.last_ram_value = value
            self.ram_reads += 1
            drives["ram_line"] = True
        elif self.cpu.phase == "EXECUTE":
            value = self.cpu.acc.value & 0xFF
            self._write_ram_byte(addr, value)
            self.last_ram_addr = addr
            self.last_ram_value = value
            self.ram_writes += 1
            drives["ram_line"] = True
        elif self.cpu.phase == "WRITEBACK":
            drives["ram_line"] = True

        # Periodic RAM -> HDD synchronization (toy model).
        cycle = self.cpu.cycle_count
        if cycle > 0 and cycle % 8 == 0 and cycle != self._last_synced_cycle:
            self._last_synced_cycle = cycle
            sector = (cycle // 8) % self.hdd_sector_count
            start = (sector * self.hdd_sector_size) % self.ram_size
            chunk = bytes(self._read_ram_byte((start + i) & 0xFF) for i in range(self.hdd_sector_size))
            self.hdd[sector] = chunk
            self.last_hdd_sector = sector
            self.hdd_writes += 1
            drives["hdd_line"] = True

    def memory_screen_lines(self) -> list[str]:
        used_cells = [i for i in range(self.ram_size) if self._read_ram_byte(i) != 0]
        used_count = len(used_cells)
        used_preview = " ".join(f"{i:02X}" for i in used_cells[:16]) if used_cells else "-"

        lines: list[str] = [
            "RAM/HDD monitor:",
            "Machine model: analog wires + RC clock + analog RAM cells + transistor CPU gates",
            f"Clock: Vcap={self.clock_cap_v:.2f}V level={self.clock_level} est={self.clock_hz_estimate:.2f} Hz",
            f"RAM size: {self.ram_size} bytes (volatile analog cells) | reads={self.ram_reads} writes={self.ram_writes}",
            f"RAM used cells (non-zero): {used_count}/{self.ram_size}",
            f"Used addr preview: {used_preview}",
            f"HDD: {self.hdd_sector_count} sectors x {self.hdd_sector_size} bytes | writes={self.hdd_writes}",
            f"Last RAM op: addr=0x{self.last_ram_addr:02X} value=0x{self.last_ram_value:02X}",
            f"Last HDD sync sector: {self.last_hdd_sector}",
            "",
            "RAM hex dump (0x00..0x3F):",
        ]

        cols = 8
        rows = 8
        for row in range(rows):
            start = row * cols
            chunk = [self._read_ram_byte(start + i) for i in range(cols)]
            hexs = " ".join(f"{b:02X}" for b in chunk)
            lines.append(f"{start:02X}: {hexs}")

        lines.append("")
        lines.append("HDD sector preview:")
        for sector in range(2):
            chunk = self.hdd[sector]
            hexs = " ".join(f"{b:02X}" for b in chunk[:8])
            lines.append(f"S{sector:02d}: {hexs} ...")

        lines.append("")
        lines.append(
            "Wire voltages (V): "
            f"CLK={self.wire_voltage['clock_line']:.2f} "
            f"CTRL={self.wire_voltage['control_line']:.2f} "
            f"ALU={self.wire_voltage['alu_bus']:.2f} "
            f"MEM={self.wire_voltage['memory_bus']:.2f}"
        )

        if not self.boot_ready:
            lines.append("")
            lines.append("Status: waiting for power/current to keep RAM active.")
        return lines
